SAT/SAT.UI.MVC/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAT.DATA.EF.Models;

namespace SAT.UI.MVC.Controllers
{
    public class CoursesController : Controller
    {
        private readonly SATContext _context;

        public CoursesController(SATContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
              return _context.Courses != null ? 
                          View(await _context.Courses.ToListAsync()) :
                          Problem("Entity set 'SATContext.Courses'  is null.");
        }

        public async Task<IActionResult> TiledCourses()
        {
            return _context.Courses != null ?
                         View(await _context.Courses.ToListAsync()) :
                         Problem("Entity set 'SATContext.Courses'  is null.");
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }
        [Authorize(Roles = "Admin")]
        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseId,CourseName,CourseDescription,CreditHours,Curriculum,Notes,IsActive")] Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        [Authorize(Roles = "Admin")]
        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CourseId,CourseName,CourseDescription,CreditHours,Curriculum,Notes,IsActive")] Course course)
        {
            if (id != course.CourseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.CourseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }
        [Authorize(Roles = "Admin")]
        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.CourseId == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Courses == null)
            {
                return Problem("Entity set 'SATContext.Courses'  is null.");
            }
            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                _context.Courses.Remove(course);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
          return (_context.Courses?.Any(e => e.CourseId == id)).GetValueOrDefault();
        }
    }
}

SAT/SAT.UI.MVC/Controllers/ScheduledClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAT.DATA.EF.Models;

namespace SAT.UI.MVC.Controllers
{
    public class ScheduledClassesController : Controller
    {
        private readonly SATContext _context;

        public ScheduledClassesController(SATContext context)
        {
            _context = context;
        }

        // GET: ScheduledClasses
        public async Task<IActionResult> Index()
        {
            var sATContext = _context.ScheduledClasses.Include(s => s.Course).Include(s => s.Scs);
            return View(await sATContext.ToListAsync());
        }

        // GET: ScheduledClasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ScheduledClasses == null)
            {
                return NotFound();
            }

            var scheduledClass = await _context.ScheduledClasses
                .Include(s => s.Course)
                .Include(s => s.Scs)
                .FirstOrDefaultAsync(m => m.ScheduledClassId == id);
            if (scheduledClass == null)
            {
                return NotFound();
            }

            return View(scheduledClass);
        }
        [Authorize(Roles = "Admin")]
        // GET: ScheduledClasses/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseDescription");
            ViewData["Scsid"] = new SelectList(_context.ScheduledClassStatuses, "Scsid", "Scsname");
            return View();
        }

        // POST: ScheduledClasses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ScheduledClassId,CourseId,StartDate,EndDate,InstructorName,Location,Scsid")] ScheduledClass scheduledClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(scheduledClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseDescription", scheduledClass.CourseId);
            ViewData["Scsid"] = new SelectList(_context.ScheduledClassStatuses, "Scsid", "Scsname", scheduledClass.Scsid);
            return View(scheduledClass);
        }
        [Authorize(Roles = "Admin")]
        // GET: ScheduledClasses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ScheduledClasses == null)
            {
                return NotFound();
            }

            var scheduledClass = await _context.ScheduledClasses.FindAsync(id);
            if (scheduledClass == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseDescription", scheduledClass.CourseId);
            ViewData["Scsid"] = new SelectList(_context.ScheduledClassStatuses, "Scsid", "Scsname", scheduledClass.Scsid);
            return View(scheduledClass);
        }

        // POST: ScheduledClasses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ScheduledClassId,CourseId,StartDate,EndDate,InstructorName,Location,Scsid")] ScheduledClass scheduledClass)
        {
            if (id != scheduledClass.ScheduledClassId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(scheduledClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScheduledClassExists(scheduledClass.ScheduledClassId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "CourseId", "CourseDescription", scheduledClass.CourseId);
            ViewData["Scsid"] = new SelectList(_context.ScheduledClassStatuses, "Scsid", "Scsname", scheduledClass.Scsid);
            return View(scheduledClass);
        }
        [Authorize(Roles = "Admin")]
        // GET: ScheduledClasses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ScheduledClasses == null)
            {
                return NotFound();
            }

            var scheduledClass = await _context.ScheduledClasses
                .Include(s => s.Course)
                .Include(s => s.Scs)
                .FirstOrDefaultAsync(m => m.ScheduledClassId == id);
            if (scheduledClass == null)
            {
                return NotFound();
            }

            return View(scheduledClass);
        }

        // POST: ScheduledClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ScheduledClasses == null)
            {
                return Problem("Entity set 'SATContext.ScheduledClasses'  is null.");
            }
            var scheduledClass = await _context.ScheduledClasses.FindAsync(id);
            if (scheduledClass != null)
            {
                _context.ScheduledClasses.Remove(scheduledClass);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ScheduledClassExists(int id)
        {
          return (_context.ScheduledClasses?.Any(e => e.ScheduledClassId == id)).GetValueOrDefault();
        }
    }
}

SAT/SAT.UI.MVC/Views/Courses/Create.cshtml
@model SAT.DATA.EF.Models.Course

@{
    ViewData["Title"] = "Create Course";
}


<section class="contact_section layout_padding">

    <div class="heading_container my-4">
        <h4>Create New: </h4>
        <h2>
            Course
        </h2>

    </div>
    <div class="">
        <div class="px-5">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="CourseName" class="control-label"></label>
                            <input asp-for="CourseName" class="form-control" />
                            <span asp-validation-for="CourseName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CourseDescription" class="control-label"></label>
                            <input asp-for="CourseDescription" class="form-control" />
                            <span asp-validation-for="CourseDescription" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CreditHours" class="control-label"></label>
                            <input asp-for="CreditHours" class="form-control" />
                            <span asp-validation-for="CreditHours" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Curriculum" class="control-label"></label>
                            <input asp-for="Curriculum" class="form-control" />
                            <span asp-validation-for="Curriculum" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Notes" class="control-label"></label>
                            <input asp-for="Notes" class="form-control" />
                            <span asp-validation-for="Notes" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-dark" />
                            <a class="btn btn-dark" asp-action="Index">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAT/SAT.UI.MVC/Views/Courses/Delete.cshtml
@model SAT.DATA.EF.Models.Course

@{
    ViewData["Title"] = "Delete Course";
}
<section class="contact_section layout_padding">

    <div class="heading_container my-4">
        <h3 class="text-danger">
            Are you sure you want to delete:
        </h3>
        <h2>@Model.CourseName</h2>
    </div>



    <div class="">
        <div class="px-5">
            <div class="row justify-content-center">
                <div class="col-md-4">

                    <div>
                        <h4>Course</h4>
                        <hr />
                        <dl class="row">
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.CourseName)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.CourseName)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.CourseDescription)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.CourseDescription)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.CreditHours)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.CreditHours)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Curriculum)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Curriculum)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Notes)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Notes)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.IsActive)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.IsActive)
                            </dd>
                        </dl>
                    </div>

                    <div>
                        <form asp-action="Delete">
                            <input type="hidden" asp-for="CourseId" />
                            <input type="submit" value="Delete" class="btn btn-danger" />
                            <a class="btn btn-dark" asp-action="Index">Cancel</a>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>

</section>

SAT/SAT.UI.MVC/Views/Courses/Details.cshtml
@model SAT.DATA.EF.Models.Course

@{
    ViewData["Title"] = "Details";
}

<section class="contact_section layout_padding">

    <div class="heading_container my-4">
        <h2>@Model.CourseName</h2>
    </div>



    <div class="">
        <div class="px-5">
            <div class="row justify-content-center">
                <div class="col-md-4">

                    <div>
                        <hr />
                        <dl class="row">
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.CourseName)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.CourseName)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.CourseDescription)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.CourseDescription)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.CreditHours)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.CreditHours)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Curriculum)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Curriculum)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.Notes)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.Notes)
                            </dd>
                            <dt class="col-sm-4">
                                @Html.DisplayNameFor(model => model.IsActive)
                            </dt>
                            <dd class="col-sm-8">
                                @Html.DisplayFor(model => model.IsActive)
                            </dd>
                        </dl>
                    </div>

                    <div>
                        <a class="btn btn-dark" asp-action="Edit" asp-route-id="@Model.CourseId">Edit</a> 
                        <a class="btn btn-dark" asp-action="Index">Cancel</a>
                    </div>

                </div>
            </div>
        </div>
    </div>

</section>

SAT/SAT.UI.MVC/Views/Courses/Edit.cshtml
@model SAT.DATA.EF.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<section class="contact_section layout_padding">

    <div class="heading_container my-4">
        <h2>
            @Model.CourseName
        </h2>

    </div>
    <div class="">
        <div class="px-5">
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="CourseId" />
                        <div class="form-group">
                            <label asp-for="CourseName" class="control-label"></label>
                            <input asp-for="CourseName" class="form-control" />
                            <span asp-validation-for="CourseName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CourseDescription" class="control-label"></label>
                            <input asp-for="CourseDescription" class="form-control" />
                            <span asp-validation-for="CourseDescription" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CreditHours" class="control-label"></label>
                            <input asp-for="CreditHours" class="form-control" />
                            <span asp-validation-for="CreditHours" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Curriculum" class="control-label"></label>
                            <input asp-for="Curriculum" class="form-control" />
                            <span asp-validation-for="Curriculum" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Notes" class="control-label"></label>
                            <input asp-for="Notes" class="form-control" />
                            <span asp-validation-for="Notes" class="text-danger"></span>
                        </div>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-dark" />
                            <a class="btn btn-dark" asp-action="Index">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAT/SAT.UI.MVC/Views/Courses/Index.cshtml
@model IEnumerable<SAT.DATA.EF.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<section class="contact_section layout_padding">

    <div class="heading_container my-4">
        <h2>
            Courses
        </h2>
        @if (User.IsInRole("Admin"))
        {

            <a class="btn btn-dark my-2" asp-action="Create">Create New</a>
        }
        <a class="btn btn-dark my-2" asp-action="TiledCourses">Tiled View</a>

    </div>
    <div class="">
        <div class="px-5">
            <table class="table table-dark text-center">
                <thead>
                    <tr>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.CourseName)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.CourseDescription)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.CreditHours)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.Curriculum)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.Notes)
                        </th>
                        <th class="text-center">
                            @Html.DisplayNameFor(model => model.IsActive)
                        </th>
                        @if (User.IsInRole("Admin"))
                        {
                            <th>Actions</th>
                        }
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CourseName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CourseDescription)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreditHours)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Curriculum)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Notes)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsActive)
                            </td>

                            @if (User.IsInRole("Admin"))
                            {
                                <td>
                                    <a class="btn btn-outline-light" asp-action="Edit" asp-route-id="@item.CourseId">Edit</a>
                                    <a class="btn btn-outline-light" asp-action="Details" asp-route-id="@item.CourseId">Details</a>
                                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.CourseId">Delete</a>
                                </td>
                            }
                            
                        </tr>
                    }
                </tbody>
            </table>

        </div>
    </div>
</section>

@section Scripts{
    <script>
        $(document).ready(function () {
            //Update the selector to target the element with the table class
            $('.table').DataTable();
        });
    </script>
}

SAT/SAT.UI.MVC/Views/Courses/TiledCourses.cshtml
@model IEnumerable<SAT.DATA.EF.Models.Course>

@{
    ViewData["Title"] = "Courses";
}

<section class="contact_section layout_padding">

    <div class="heading_container my-4">
        <h2>
            Courses
        </h2>
        @if (User.IsInRole("Admin"))
        {

            <a class="btn btn-dark my-2" asp-action="Create">Create New</a>
        }
            <a class="btn btn-dark my-2" asp-action="Index">Table View</a>

    </div>
    <div class="">
        <div class="px-5">
            <div class="row justify-content-center">
                @foreach (var item in Model)
                {
                    <div class="container col-md-3 course-card bg-dark text-center rounded text-light m-3 p-2">
                        <a class="text-decoration-none text-light" asp-action="Index" asp-controller="ScheduledClasses">
                            <div class="border border-light rounded mb-2">
                                <h3>@Html.DisplayFor(modelItem => item.CourseName)</h3>

                                <span>Credit Hours: @Html.DisplayFor(modelItem => item.CreditHours)</span>

                                <p>@Html.DisplayFor(modelItem => item.CourseDescription)</p>

                                <p>@Html.DisplayFor(modelItem => item.Curriculum)</p>

                                <p>@Html.DisplayFor(modelItem => item.Notes)</p>
                            </div>
                        </a>
                        <div>
                            @if (User.IsInRole("Admin"))
                            {
                            <a class="btn btn-outline-light" asp-action="Edit" asp-route-id="@item.CourseId">Edit</a>
                            <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.CourseId">Delete</a>
                            }
                        </div>

                    </div>
                }
            </div>

        </div>
    </div>
</section>